#!/usr/bin/python3

def factorize_number(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append(i)
            factors.append(n // i)
            break
    return factors

def factorize_file(file_path):
    with open(file_path, 'r') as file:
        numbers = file.readlines()

    for num in numbers:
        num = int(num)
        factors = factorize_number(num)
        print(f"{num}={max(factors)}*{min(factors)}")

if __name__ == "__main__":
    file_path = 'tests/test00'
    factorize_file(file_path)
